export const categoryOptions = [
    "E-Commerce",
    "Healthcare",
    "FinTech",
    "Real Estate",
    "Food & Beverage",
    "SaaS",
    "Education",
    "Fashion",
    "Travel",
    "Product",
    "Advertising",
    "Design",
    "Other",
];

export const tagOptions = [
    "SEO",
    "PPC",
    "Social Media",
    "Content Marketing",
    "Lead Gen",
    "Branding",
    "PR",
    "Analytics",
    "Email Marketing",
    "CRO",
    "Influencer Marketing",
    "Social Ads",
    "Virtual Tours",
    "Video Marketing",
    "Ad Film",
    "Fashion",
    "Motion",
    "Design",
    "Product",
];
